services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    rootDir: Backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: BACKEND_URL
        sync: false
